/**
 * Real geography, hand-resolved from each destination's `region` text
 * against its actual country/US state — not derived or guessed at render
 * time. `region` alone can't drive this directly: most destinations' region
 * is a country name and resolves mechanically ("Portugal" -> PRT, "Maine,
 * USA" -> ME), but a real minority are sub-regions, multi-country/
 * multi-state names, or territories ("Central America", "Tierra del Fuego"
 * / "Argentina & Chile", "Glacier & Waterton Lakes" / "Montana, USA &
 * Alberta, Canada") that need a human call on the primary country/state.
 * This is exactly the kind of fact `docs/final-architecture-plan.md`
 * expects to eventually live in a real `countryCode` column on `places`;
 * this file is a stand-in for that until the Place migration lands.
 *
 * `type: 'country'` -> ISO 3166-1 alpha-3. `type: 'us-state'` -> the USPS
 * two-letter abbreviation (also used for Puerto Rico's "PR", a real,
 * valid USPS abbreviation for a US territory, not a state).
 */
export type DestinationLocation = { type: 'country' | 'us-state'; code: string };

export const DESTINATION_LOCATIONS: Record<string, DestinationLocation> = {
  acadia: { type: 'us-state', code: 'ME' },
  algarve: { type: 'country', code: 'PRT' },
  amalfi: { type: 'country', code: 'ITA' },
  amsterdam: { type: 'country', code: 'NLD' },
  andalucia: { type: 'country', code: 'ESP' },
  angkor: { type: 'country', code: 'KHM' },
  antarctica: { type: 'country', code: 'ATA' },
  'arches-canyonlands': { type: 'us-state', code: 'UT' },
  'argentine-lake-district': { type: 'country', code: 'ARG' },
  aruba: { type: 'country', code: 'ABW' },
  aspen: { type: 'us-state', code: 'CO' },
  atacama: { type: 'country', code: 'CHL' },
  athens: { type: 'country', code: 'GRC' },
  azores: { type: 'country', code: 'PRT' },
  'badlands-black-hills': { type: 'us-state', code: 'SD' },
  bagan: { type: 'country', code: 'MMR' },
  bahamas: { type: 'country', code: 'BHS' },
  bali: { type: 'country', code: 'IDN' },
  banff: { type: 'country', code: 'CAN' },
  bangkok: { type: 'country', code: 'THA' },
  barbados: { type: 'country', code: 'BRB' },
  barcelona: { type: 'country', code: 'ESP' },
  'basque-country': { type: 'country', code: 'ESP' },
  'bavaria-munich': { type: 'country', code: 'DEU' },
  beijing: { type: 'country', code: 'CHN' },
  'belfast-giants-causeway': { type: 'country', code: 'GBR' },
  belize: { type: 'country', code: 'BLZ' },
  'bend-crater-lake': { type: 'us-state', code: 'OR' },
  berlin: { type: 'country', code: 'DEU' },
  bhutan: { type: 'country', code: 'BTN' },
  'big-island': { type: 'us-state', code: 'HI' },
  'black-forest': { type: 'country', code: 'DEU' },
  borabora: { type: 'country', code: 'PYF' },
  bordeaux: { type: 'country', code: 'FRA' },
  borneo: { type: 'country', code: 'MYS' },
  botswana: { type: 'country', code: 'BWA' },
  budapest: { type: 'country', code: 'HUN' },
  buenosaires: { type: 'country', code: 'ARG' },
  canaries: { type: 'country', code: 'ESP' },
  'cape-cod-islands': { type: 'us-state', code: 'MA' },
  'cape-town': { type: 'country', code: 'ZAF' },
  chamonix: { type: 'country', code: 'FRA' },
  champagne: { type: 'country', code: 'FRA' },
  'charleston-savannah': { type: 'us-state', code: 'SC' },
  'chiang-mai': { type: 'country', code: 'THA' },
  chiapas: { type: 'country', code: 'MEX' },
  chicago: { type: 'us-state', code: 'IL' },
  'chilean-lake-district': { type: 'country', code: 'CHL' },
  churchill: { type: 'country', code: 'CAN' },
  'colombian-andes': { type: 'country', code: 'COL' },
  'colombian-caribbean': { type: 'country', code: 'COL' },
  copenhagen: { type: 'country', code: 'DNK' },
  cornwall: { type: 'country', code: 'GBR' },
  'costa-rica': { type: 'country', code: 'CRI' },
  cotswolds: { type: 'country', code: 'GBR' },
  croatia: { type: 'country', code: 'HRV' },
  'death-valley': { type: 'us-state', code: 'CA' },
  'denali-interior': { type: 'us-state', code: 'AK' },
  dolomites: { type: 'country', code: 'ITA' },
  'douro-valley-porto': { type: 'country', code: 'PRT' },
  dubai: { type: 'country', code: 'ARE' },
  'ecuadorian-andes': { type: 'country', code: 'ECU' },
  edinburgh: { type: 'country', code: 'GBR' },
  egypt: { type: 'country', code: 'EGY' },
  'el-chalten': { type: 'country', code: 'ARG' },
  ethiopia: { type: 'country', code: 'ETH' },
  everglades: { type: 'us-state', code: 'FL' },
  falklands: { type: 'country', code: 'FLK' },
  'faroe-islands': { type: 'country', code: 'DNK' },
  fiji: { type: 'country', code: 'FJI' },
  fjords: { type: 'country', code: 'NOR' },
  galapagos: { type: 'country', code: 'ECU' },
  gbr: { type: 'country', code: 'AUS' },
  ghana: { type: 'country', code: 'GHA' },
  'glacier-waterton': { type: 'us-state', code: 'MT' },
  grandcanyon: { type: 'us-state', code: 'AZ' },
  'great-smoky-mountains': { type: 'us-state', code: 'TN' },
  greenland: { type: 'country', code: 'DNK' },
  guatemala: { type: 'country', code: 'GTM' },
  'guilin-yangshuo': { type: 'country', code: 'CHN' },
  havana: { type: 'country', code: 'CUB' },
  hokkaido: { type: 'country', code: 'JPN' },
  hongkong: { type: 'country', code: 'CHN' },
  'hudson-valley': { type: 'us-state', code: 'NY' },
  iceland: { type: 'country', code: 'ISL' },
  ireland: { type: 'country', code: 'IRL' },
  istanbul: { type: 'country', code: 'TUR' },
  jamaica: { type: 'country', code: 'JAM' },
  jordan: { type: 'country', code: 'JOR' },
  'joshua-tree': { type: 'us-state', code: 'CA' },
  kaziranga: { type: 'country', code: 'IND' },
  kenya: { type: 'country', code: 'KEN' },
  kerala: { type: 'country', code: 'IND' },
  komodo: { type: 'country', code: 'IDN' },
  kruger: { type: 'country', code: 'ZAF' },
  kyrgyzstan: { type: 'country', code: 'KGZ' },
  ladakh: { type: 'country', code: 'IND' },
  'lake-district': { type: 'country', code: 'GBR' },
  lapland: { type: 'country', code: 'FIN' },
  lisbon: { type: 'country', code: 'PRT' },
  lofoten: { type: 'country', code: 'NOR' },
  london: { type: 'country', code: 'GBR' },
  'los-cabos': { type: 'country', code: 'MEX' },
  luangprabang: { type: 'country', code: 'LAO' },
  madagascar: { type: 'country', code: 'MDG' },
  madeira: { type: 'country', code: 'PRT' },
  maldives: { type: 'country', code: 'MDV' },
  mallorca: { type: 'country', code: 'ESP' },
  'marlborough-abel-tasman': { type: 'country', code: 'NZL' },
  maui: { type: 'us-state', code: 'HI' },
  mauritius: { type: 'country', code: 'MUS' },
  mendoza: { type: 'country', code: 'ARG' },
  mexicocity: { type: 'country', code: 'MEX' },
  'milford-sound-fiordland': { type: 'country', code: 'NZL' },
  mongolia: { type: 'country', code: 'MNG' },
  'monterey-big-sur': { type: 'us-state', code: 'CA' },
  morocco: { type: 'country', code: 'MAR' },
  namibia: { type: 'country', code: 'NAM' },
  napa: { type: 'us-state', code: 'CA' },
  nepal: { type: 'country', code: 'NPL' },
  'new-orleans': { type: 'us-state', code: 'LA' },
  nicaragua: { type: 'country', code: 'NIC' },
  'nice-riviera': { type: 'country', code: 'FRA' },
  'north-cascades': { type: 'us-state', code: 'WA' },
  'north-island': { type: 'country', code: 'NZL' },
  'nova-scotia': { type: 'country', code: 'CAN' },
  nyc: { type: 'us-state', code: 'NY' },
  oaxaca: { type: 'country', code: 'MEX' },
  okinawa: { type: 'country', code: 'JPN' },
  olympic: { type: 'us-state', code: 'WA' },
  pakistan: { type: 'country', code: 'PAK' },
  palau: { type: 'country', code: 'PLW' },
  palawan: { type: 'country', code: 'PHL' },
  panama: { type: 'country', code: 'PAN' },
  pantanal: { type: 'country', code: 'BRA' },
  'papua-new-guinea': { type: 'country', code: 'PNG' },
  paris: { type: 'country', code: 'FRA' },
  peru: { type: 'country', code: 'PER' },
  'peruvian-amazon': { type: 'country', code: 'PER' },
  piedmont: { type: 'country', code: 'ITA' },
  prague: { type: 'country', code: 'CZE' },
  provence: { type: 'country', code: 'FRA' },
  'puerto-rico': { type: 'us-state', code: 'PR' },
  puglia: { type: 'country', code: 'ITA' },
  'punta-cana': { type: 'country', code: 'DOM' },
  'quebec-city': { type: 'country', code: 'CAN' },
  queenstown: { type: 'country', code: 'NZL' },
  rajaampat: { type: 'country', code: 'IDN' },
  'rajasthan-golden-triangle': { type: 'country', code: 'IND' },
  redwood: { type: 'us-state', code: 'CA' },
  rio: { type: 'country', code: 'BRA' },
  rioja: { type: 'country', code: 'ESP' },
  rivieramaya: { type: 'country', code: 'MEX' },
  'rocky-mountain': { type: 'us-state', code: 'CO' },
  rome: { type: 'country', code: 'ITA' },
  rwanda: { type: 'country', code: 'RWA' },
  'san-miguel-guanajuato': { type: 'country', code: 'MEX' },
  santorini: { type: 'country', code: 'GRC' },
  sardinia: { type: 'country', code: 'ITA' },
  'scottish-highlands-skye': { type: 'country', code: 'GBR' },
  sedona: { type: 'us-state', code: 'AZ' },
  seoul: { type: 'country', code: 'KOR' },
  'sequoia-kings-canyon': { type: 'us-state', code: 'CA' },
  seychelles: { type: 'country', code: 'SYC' },
  sicily: { type: 'country', code: 'ITA' },
  singapore: { type: 'country', code: 'SGP' },
  snowdonia: { type: 'country', code: 'GBR' },
  'southeast-alaska': { type: 'us-state', code: 'AK' },
  srilanka: { type: 'country', code: 'LKA' },
  'st-andrews-fife': { type: 'country', code: 'GBR' },
  svalbard: { type: 'country', code: 'NOR' },
  swissalps: { type: 'country', code: 'CHE' },
  sydney: { type: 'country', code: 'AUS' },
  taiwan: { type: 'country', code: 'TWN' },
  tanzania: { type: 'country', code: 'TZA' },
  tasmania: { type: 'country', code: 'AUS' },
  'tbilisi-caucasus': { type: 'country', code: 'GEO' },
  'texas-hill-country': { type: 'us-state', code: 'TX' },
  thailand: { type: 'country', code: 'THA' },
  'tierra-del-fuego': { type: 'country', code: 'ARG' },
  'tokyo-kyoto': { type: 'country', code: 'JPN' },
  'torres-del-paine': { type: 'country', code: 'CHL' },
  'turks-caicos': { type: 'country', code: 'TCA' },
  tuscany: { type: 'country', code: 'ITA' },
  uganda: { type: 'country', code: 'UGA' },
  uluru: { type: 'country', code: 'AUS' },
  'upper-peninsula': { type: 'us-state', code: 'MI' },
  uyuni: { type: 'country', code: 'BOL' },
  uzbekistan: { type: 'country', code: 'UZB' },
  'vancouver-island': { type: 'country', code: 'CAN' },
  venice: { type: 'country', code: 'ITA' },
  vermont: { type: 'us-state', code: 'VT' },
  vienna: { type: 'country', code: 'AUT' },
  vietnam: { type: 'country', code: 'VNM' },
  whistler: { type: 'country', code: 'CAN' },
  yellowstone: { type: 'us-state', code: 'WY' },
  yosemite: { type: 'us-state', code: 'CA' },
  zambia: { type: 'country', code: 'ZMB' },
  zimbabwe: { type: 'country', code: 'ZWE' },
  'zion-bryce': { type: 'us-state', code: 'UT' },
};

/** Falls back to the first 3 letters of the id (uppercased) for any
 * destination somehow missing from the table above — should never happen
 * for the current 200, but a new destination added without updating this
 * file shouldn't crash the stamp UI, just show a slightly-wrong code
 * until someone fills it in. */
export function locationCodeFor(destinationId: string): string {
  return locationFor(destinationId).code;
}

/** Same fallback as locationCodeFor, but returns the type too — needed
 * wherever US-state vs. country changes the rule (e.g. stamp ink color). */
export function locationFor(destinationId: string): DestinationLocation {
  const loc = DESTINATION_LOCATIONS[destinationId];
  if (loc) return loc;
  return { type: 'country', code: destinationId.replace(/-/g, '').slice(0, 3).toUpperCase() };
}
