/**
 * GENERATED by scripts/generate-interest-thresholds.ts — do not hand-edit.
 *
 * Score cutoffs per interest, used to derive a signature tier when a
 * destination has none authored. Derived from the live catalogue: within
 * each interest, the 90th and 75th percentiles of authored, non-N/A
 * scores, floored at 8 and 6 respectively so a thinly-authored interest
 * cannot crown a mediocre score.
 *
 * Regenerate after material content changes.
 * Generated: 2026-09-07 from 200 destinations.
 */
export interface InterestThreshold {
  /** score at or above which a destination is notable for this interest */
  signature: number;
  /** score at or above which it is a genuine draw */
  strong: number;
  /** score at or above which it is present but not a reason to come */
  casual: number;
}

export const INTEREST_THRESHOLDS: Record<string, InterestThreshold> = {
  wildlifeViewing: { signature: 8, strong: 6, casual: 4 },
  birding: { signature: 8, strong: 6, casual: 4 },
  safari: { signature: 10, strong: 8.75, casual: 4 },
  whaleWatching: { signature: 8.100000000000001, strong: 8, casual: 4 },
  scenicLandscapes: { signature: 9, strong: 8, casual: 4 },
  landscapePhotography: { signature: 9, strong: 8, casual: 4 },
  nationalParks: { signature: 9, strong: 8, casual: 4 },
  campingBackcountry: { signature: 9, strong: 8, casual: 4 },
  stargazing: { signature: 8, strong: 6, casual: 4 },
  auroraChasing: { signature: 8, strong: 6, casual: 4 },
  geologyVolcanoes: { signature: 9, strong: 8, casual: 4 },
  wildflowerBlooms: { signature: 8, strong: 6, casual: 4 },
  hiking: { signature: 8, strong: 6, casual: 4 },
  mountaineering: { signature: 9, strong: 7, casual: 4 },
  cyclingRoad: { signature: 8, strong: 6, casual: 4 },
  mountainBiking: { signature: 8, strong: 6, casual: 4 },
  skiingSnowboarding: { signature: 9, strong: 6, casual: 4 },
  surfing: { signature: 8, strong: 6, casual: 4 },
  diving: { signature: 9, strong: 6, casual: 4 },
  sailing: { signature: 8, strong: 6, casual: 4 },
  kayakingRafting: { signature: 8, strong: 6, casual: 4 },
  adventureSports: { signature: 8, strong: 6, casual: 4 },
  golf: { signature: 8, strong: 6, casual: 4 },
  fishing: { signature: 8, strong: 6, casual: 4 },
  horsebackRiding: { signature: 8, strong: 6, casual: 4 },
  trailRunning: { signature: 8, strong: 6, casual: 4 },
  historyArchaeology: { signature: 8.200000000000003, strong: 7, casual: 4 },
  museumsArt: { signature: 9, strong: 7, casual: 4 },
  architecture: { signature: 9, strong: 8, casual: 4 },
  cityExploration: { signature: 8, strong: 7, casual: 4 },
  indigenousCultures: { signature: 8, strong: 6, casual: 4 },
  religiousSites: { signature: 8, strong: 6.75, casual: 4 },
  festivals: { signature: 8, strong: 6, casual: 4 },
  traditionalCrafts: { signature: 8, strong: 6, casual: 4 },
  streetFood: { signature: 9, strong: 7, casual: 4 },
  fineDining: { signature: 8, strong: 7, casual: 4 },
  wineSpirits: { signature: 8.100000000000009, strong: 6, casual: 4 },
  coffeeTea: { signature: 8, strong: 6, casual: 4 },
  beachesSwimming: { signature: 8.200000000000003, strong: 7, casual: 4 },
  sunbathing: { signature: 9, strong: 7, casual: 4 },
  luxuryHotels: { signature: 9, strong: 8, casual: 4 },
  allInclusive: { signature: 8.7, strong: 7, casual: 4 },
  spaWellness: { signature: 8, strong: 6, casual: 4 },
  hotSprings: { signature: 8, strong: 7, casual: 4 },
  yogaRetreats: { signature: 8.3, strong: 7, casual: 4 },
  themeParks: { signature: 8, strong: 6.75, casual: 4 },
  nightlife: { signature: 8, strong: 6, casual: 4 },
  shopping: { signature: 8, strong: 6, casual: 4 },
  familyFun: { signature: 8, strong: 7, casual: 4 },
  spectatorSports: { signature: 8, strong: 7, casual: 4 },
  roadtrip: { signature: 8, strong: 6, casual: 4 },
};

/** Fallback for an interest with no generated entry. */
export const DEFAULT_THRESHOLD: InterestThreshold = { signature: 8, strong: 6, casual: 4 };

