import { readFileSync } from 'fs';
import { join } from 'path';
import { eq } from 'drizzle-orm';
import { drizzle as drizzlePostgres } from 'drizzle-orm/postgres-js';
import postgres from 'postgres';
import { places, adminAuditLog } from '../src/lib/db/schema';

const KEY = 'windSports';

const OVERVIEWS: Record<string, string> = {
  dubai: 'Kite Beach, Dubai\'s official kitesurfing spot, actually has wind nearly year-round — summer\'s Shamal winds (May through October) can gust 15-30 knots. Winter (December through April) is genuinely the preferred season, but mainly for comfort: summer temperatures above 40°C make sessions punishing even when the wind is good.',
  croatia: 'Viganj, on the Pelješac Peninsula, is one of the best-known windsurfing and kitesurfing spots in Croatia — a natural wind funnel between the peninsula and the island of Korčula. This is a real seasonal destination, not a year-round one: the spot is essentially closed in the depths of winter, and the season runs May to September, peaking June to August.',
  srilanka: 'Kalpitiya\'s Puttalam Lagoon has two real, distinct wind seasons — not a year-round destination. The main season (May through October) is the stronger of the two; a secondary, lighter season runs December through February. Between the two, March through April is a genuine "gap season" when the lagoon goes glassy and calm.',
  tanzania: 'Paje, on Zanzibar\'s east coast, is a world-class kitesurfing beach with two real monsoon wind seasons — the stronger Kusi (May through October) and the lighter Kaskazi (December through March). April, in the middle of Tanzania\'s long rains, is the genuine dead spot; November is also a quiet in-between month.',
  barbados: 'Silver Sands is reliably windy essentially year-round, with one real exception: the trade winds drop off hard from July through September. Outside that window, this is a dependable, low-key Caribbean wind-sports base.',
  lisbon: 'Guincho, near Cascais, made its name hosting PWA World Cup windsurfing events through the 1990s, powered by the "nortada" — a persistent summer northerly wind. This is a real seasonal destination built around summer: June through September is the window, and winter is genuinely too calm for it.',
  ireland: 'Brandon Bay and the Maharees peninsula, in County Kerry, are Ireland\'s best-known windsurfing waters — the Maharees hosted PWA wave-sailing events in 2000, 2001, and 2002. This is a real seasonal destination built around Atlantic storm season: September through February is when the wind and waves combine; the rest of the year is calmer, more moderate sailing.',
  cornwall: 'Watergate Bay, near Newquay, is regularly rated one of the best wind-and-wave combination spots in Europe, home to the "Extreme Academy" kite school. Autumn and winter Atlantic storms bring the biggest, most reliable wind; summer is genuinely lighter, with real breeze on only about half of days.',
  gbr: 'The Whitsundays, especially Dingo Beach and Whitehaven Beach, are a real kitesurfing draw within the Great Barrier Reef Marine Park — consistent trade winds and tide-flattened water. March through August is the reliable window; January and February, in the middle of cyclone season, are genuinely the least reliable months.',
  mallorca: 'Pollença Bay is Mallorca\'s official kitesurfing spot, powered by the "Embat" — a thermal sea breeze that builds most afternoons in the warmer months. This is a real seasonal destination: the Embat is a summer phenomenon, active roughly April through September, and essentially inactive in winter.',
  taiwan: 'Kenting, at Taiwan\'s southern tip, is the country\'s top kitesurfing destination — the northeast monsoon brings the real season, October through March. May and June are the genuine dead spot between monsoon and typhoon season; typhoon-adjacent wind in July and August brings a real, if riskier, secondary bump.',
  bordeaux: 'The Bassin d\'Arcachon, particularly Plage des Abatilles, is a real Atlantic-coast kitesurfing and windsurfing spot near Bordeaux. The season runs March through November; December and January are genuinely too calm to plan a trip around.',
  'colombian-caribbean': 'Cabo de la Vela, in the remote La Guajira desert, gets wind on roughly 330 days a year — genuinely one of the windiest kitesurfing spots on Earth. This is a real, if difficult-to-reach, near-year-round destination (it\'s a 7-hour drive from Cartagena); May and June are the only real dip in an otherwise consistent calendar.',
  madagascar: 'Ifaty, on Madagascar\'s southwest coast, has a real, growing kitesurfing scene built around a shallow, protected lagoon. The trade-wind season runs May through September, peaking July-August; the cyclone-season months of December through March are genuinely the least reliable, and not a realistic time to plan around.',
  jamaica: 'Montego Bay and Flamingo Beach, on Jamaica\'s north coast, get consistent northeast trade winds — January and February are the most reliable months. July through October is a genuine dead stretch, coinciding with the Caribbean\'s hurricane season.',
  rio: 'Barra da Tijuca is Rio\'s real, if modest, kitesurfing beach — a genuine local scene with multiple schools, distinct from the city\'s famous postcard beaches. Wind is real but modest year-round, with September through January the more reliable stretch and March the year\'s clear low point.',
  bahamas: 'The Exumas offer real, uncrowded kitesurfing across hundreds of cays — much of it reachable only by boat. Trade winds blow reliably November through April; May through October, deep in hurricane season, is a genuine dead stretch.',
  bali: 'Sanur, on Bali\'s southeast coast, is considered the island\'s best spot for kitesurfing — though the wind here is genuinely light, and bigger kites are standard gear even in peak season. The dry-season trade winds (May through September) are the real window; the wet season (November through March) is essentially windless.',
  chicago: 'A genuine, if small, freshwater wind-sports scene exists on Lake Michigan — Montrose Beach\'s kitesurfing and windsurfing community rides real autumn storm winds, not the calmer summer lake days most visitors picture. This is a narrow, cold-water, dedicated-local scene: outside fall, there isn\'t a realistic window for the sport.',
  'cape-cod-islands': 'A modest, regional windsurfing and kitesurfing scene exists on Cape Cod Bay — real, if small-scale, summer wind. June through September is the actual window; the rest of the year is genuinely too cold and calm to plan around.',
  nyc: 'A small, real windsurfing and kitesurfing scene exists around Rockaway Beach — a niche, summer-only activity rather than a reason to visit. June through September is the only realistic window.',
  'big-island': 'Real, if modest, wind-sports activity exists on the Big Island\'s coast — genuinely minor compared to Maui\'s Ho\'okipa, and without an internationally known spot of its own. Spring through early autumn is when conditions are most workable; winter is notably calmer.',
  copenhagen: 'Amager Strandpark is Copenhagen\'s real, if modest, kitesurfing and windsurfing spot — a windsurfing club and school right in the city, an easy bike ride from downtown. May through September is when the beach is actually active; the rest of the year is genuinely too cold and calm.',
  sydney: 'Kurnell, on Botany Bay, is one of Sydney\'s best-known wind-sports spots — flat water and consistent afternoon sea breezes. The nor\'easter sea-breeze season (October through March) is the real window; April through September is a real, modest baseline rather than a dead season.',
  'nova-scotia': 'A real, if small, windsurfing and kitesurfing scene exists at Lawrencetown Beach, near Halifax — genuinely cold water year-round, with a modest, consistent local following. January and February are the only real dead months, when the cold makes it impractical.',
};

const MONTHLY: Record<string, string[]> = {
  dubai: [
    'Peak comfort-and-wind season at Kite Beach — strong wind and pleasant temperatures together.',
    'Peak comfort-and-wind season at Kite Beach — strong wind and pleasant temperatures together.',
    'Still strong, comfortable conditions at Kite Beach, easing from peak.',
    'Still strong, comfortable conditions at Kite Beach, easing from peak.',
    'One of the hottest, least comfortable stretches at Kite Beach — real wind, but the heat makes sessions tough.',
    'Shamal season at Kite Beach — genuinely windy, but extreme heat (40°C+) makes this a demanding time to visit.',
    'Shamal season at Kite Beach — genuinely windy, but extreme heat (40°C+) makes this a demanding time to visit.',
    'Shamal season at Kite Beach — genuinely windy, but extreme heat (40°C+) makes this a demanding time to visit.',
    'Shamal season at Kite Beach — genuinely windy, but extreme heat (40°C+) makes this a demanding time to visit.',
    'Cooling slightly at Kite Beach, with solid Shamal wind.',
    'One of the hottest, least comfortable stretches at Kite Beach — real wind, but the heat makes sessions tough.',
    'Comfortable temperatures returning to Kite Beach, with solid wind.',
  ],
  croatia: [
    'Outside the wind season at Viganj — kitesurfing and windsurfing here are essentially on hold in the depths of winter.',
    'Outside the wind season at Viganj — kitesurfing and windsurfing here are essentially on hold in the depths of winter.',
    'Still early in the off-season at Viganj — a little more wind than deep winter, but not yet a real kitesurfing window.',
    'Still early in the off-season at Viganj — a little more wind than deep winter, but not yet a real kitesurfing window.',
    'The wind season beginning at Viganj — real, if not yet peak, conditions.',
    'Strong, near-peak wind season at Viganj.',
    'Peak kitesurfing and windsurfing season at Viganj — the wind is strongest and most reliable.',
    'Peak kitesurfing and windsurfing season at Viganj — the wind is strongest and most reliable.',
    'Still strong wind at Viganj, easing from peak.',
    'The wind season winding down at Viganj — a real shoulder period, but noticeably weaker than summer.',
    'The wind season winding down at Viganj — a real shoulder period, but noticeably weaker than summer.',
    'Outside the wind season at Viganj — kitesurfing and windsurfing here are essentially on hold in the depths of winter.',
  ],
  srilanka: [
    'Kalpitiya\'s secondary kitesurfing season — real wind, but lighter than the summer window.',
    'Kalpitiya\'s secondary kitesurfing season — real wind, but lighter than the summer window.',
    'Kalpitiya\'s kitesurfing gap season — the lagoon goes glassy and calm, not a realistic time to plan a trip around the wind here.',
    'Kalpitiya\'s kitesurfing gap season — the lagoon goes glassy and calm, not a realistic time to plan a trip around the wind here.',
    'Kalpitiya\'s main kitesurfing season beginning — building toward peak.',
    'Peak of Kalpitiya\'s main kitesurfing season — the strongest, most reliable wind of the year.',
    'Peak of Kalpitiya\'s main kitesurfing season — the strongest, most reliable wind of the year.',
    'Peak of Kalpitiya\'s main kitesurfing season — the strongest, most reliable wind of the year.',
    'Peak of Kalpitiya\'s main kitesurfing season — the strongest, most reliable wind of the year.',
    'Kalpitiya\'s main season easing, still solid wind.',
    'Between Kalpitiya\'s two kitesurfing seasons — genuinely quiet, with neither season\'s wind mechanism active.',
    'Kalpitiya\'s secondary kitesurfing season beginning — real, if lighter, wind.',
  ],
  tanzania: [
    'Paje\'s Kaskazi wind season — real, if lighter than the Kusi season later in the year.',
    'Paje\'s Kaskazi wind season — real, if lighter than the Kusi season later in the year.',
    'Paje\'s Kaskazi wind season — real, if lighter than the Kusi season later in the year.',
    'The heart of Tanzania\'s long rains — Paje\'s quietest, least reliable month for wind all year.',
    'Paje\'s Kusi wind season beginning, building toward peak.',
    'Peak Kusi wind season at Paje — the strongest, most reliable wind of the year.',
    'Peak Kusi wind season at Paje — the strongest, most reliable wind of the year.',
    'Peak Kusi wind season at Paje — the strongest, most reliable wind of the year.',
    'Peak Kusi wind season at Paje — the strongest, most reliable wind of the year.',
    'Paje\'s Kusi season easing, still solid wind.',
    'Between Paje\'s two wind seasons — a genuinely quiet, in-between month.',
    'Paje\'s Kaskazi wind season beginning — real, if lighter, wind.',
  ],
  barbados: [
    'Peak trade-wind season at Silver Sands — the wind at its strongest and most reliable.',
    'Peak trade-wind season at Silver Sands — the wind at its strongest and most reliable.',
    'Peak trade-wind season at Silver Sands — the wind at its strongest and most reliable.',
    'Still strong, dependable trade winds at Silver Sands, easing from peak.',
    'Still strong, dependable trade winds at Silver Sands, easing from peak.',
    'Trade winds fading at Silver Sands as the summer gap approaches.',
    'The genuine off-season at Silver Sands — trade winds drop off hard, and this isn\'t a realistic window for windsurfing or kitesurfing here.',
    'The genuine off-season at Silver Sands — trade winds drop off hard, and this isn\'t a realistic window for windsurfing or kitesurfing here.',
    'The genuine off-season at Silver Sands — trade winds drop off hard, and this isn\'t a realistic window for windsurfing or kitesurfing here.',
    'Trade winds building back at Silver Sands.',
    'Trade winds building back at Silver Sands.',
    'Peak trade-wind season at Silver Sands — the wind at its strongest and most reliable.',
  ],
  lisbon: [
    'Winter at Guincho — the "nortada" summer wind isn\'t active, and this isn\'t a realistic time to plan a windsurfing trip here.',
    'Winter at Guincho — the "nortada" summer wind isn\'t active, and this isn\'t a realistic time to plan a windsurfing trip here.',
    'Still ahead of the "nortada" season at Guincho — light, building wind.',
    'Still ahead of the "nortada" season at Guincho — light, building wind.',
    'Still ahead of the "nortada" season at Guincho — light, building wind.',
    'The "nortada" wind season beginning at Guincho, building toward peak.',
    'Peak "nortada" season at Guincho — the historic home of PWA World Cup windsurfing.',
    'Peak "nortada" season at Guincho — the historic home of PWA World Cup windsurfing.',
    'Still strong "nortada" wind at Guincho, easing from peak.',
    'The "nortada" season winding down at Guincho.',
    'Winter at Guincho — the "nortada" summer wind isn\'t active, and this isn\'t a realistic time to plan a windsurfing trip here.',
    'Winter at Guincho — the "nortada" summer wind isn\'t active, and this isn\'t a realistic time to plan a windsurfing trip here.',
  ],
  ireland: [
    'Still within Atlantic storm season at Brandon Bay, easing from the winter peak.',
    'Still within Atlantic storm season at Brandon Bay, easing from the winter peak.',
    'The calmer stretch at Brandon Bay — real, moderate wind for easier sailing, but well short of the Atlantic storm season\'s power.',
    'The calmer stretch at Brandon Bay — real, moderate wind for easier sailing, but well short of the Atlantic storm season\'s power.',
    'The calmer stretch at Brandon Bay — real, moderate wind for easier sailing, but well short of the Atlantic storm season\'s power.',
    'The calmer stretch at Brandon Bay — real, moderate wind for easier sailing, but well short of the Atlantic storm season\'s power.',
    'The calmer stretch at Brandon Bay — real, moderate wind for easier sailing, but well short of the Atlantic storm season\'s power.',
    'The calmer stretch at Brandon Bay — real, moderate wind for easier sailing, but well short of the Atlantic storm season\'s power.',
    'Atlantic storm season building at Brandon Bay.',
    'Atlantic storm season building at Brandon Bay.',
    'Peak Atlantic storm season at Brandon Bay — the wind and waves that built the Maharees\' wave-sailing reputation.',
    'Peak Atlantic storm season at Brandon Bay — the wind and waves that built the Maharees\' wave-sailing reputation.',
  ],
  cornwall: [
    'Still within Atlantic storm season at Watergate Bay, easing from the winter peak.',
    'The calmer stretch at Watergate Bay, well short of the Atlantic storm season.',
    'The calmer stretch at Watergate Bay, well short of the Atlantic storm season.',
    'The calmer stretch at Watergate Bay, well short of the Atlantic storm season.',
    'A modest spring uptick at Watergate Bay — real, if inconsistent, breeze.',
    'A modest spring uptick at Watergate Bay — real, if inconsistent, breeze.',
    'Summer at Watergate Bay — genuinely the lightest wind of the year, with real breeze on only about half of days.',
    'Summer at Watergate Bay — genuinely the lightest wind of the year, with real breeze on only about half of days.',
    'Atlantic storm season building at Watergate Bay.',
    'Atlantic storm season building at Watergate Bay.',
    'Peak Atlantic storm season at Watergate Bay — the biggest, most reliable wind and waves of the year.',
    'Peak Atlantic storm season at Watergate Bay — the biggest, most reliable wind and waves of the year.',
  ],
  gbr: [
    'Cyclone season in the Whitsundays — genuinely the least reliable stretch of the year for kitesurfing.',
    'Cyclone season in the Whitsundays — genuinely the least reliable stretch of the year for kitesurfing.',
    'Trade winds picking up in the Whitsundays as cyclone season eases.',
    'Peak trade-wind season in the Whitsundays — the most consistent conditions of the year.',
    'Peak trade-wind season in the Whitsundays — the most consistent conditions of the year.',
    'Peak trade-wind season in the Whitsundays — the most consistent conditions of the year.',
    'Still strong trade winds in the Whitsundays, easing from peak.',
    'Still strong trade winds in the Whitsundays, easing from peak.',
    'A quieter stretch in the Whitsundays — real wind is possible, but well short of the April-June peak.',
    'A quieter stretch in the Whitsundays — real wind is possible, but well short of the April-June peak.',
    'A quieter stretch in the Whitsundays — real wind is possible, but well short of the April-June peak.',
    'A quieter stretch in the Whitsundays — real wind is possible, but well short of the April-June peak.',
  ],
  mallorca: [
    'Winter at Pollença Bay — the Embat thermal wind isn\'t active, and this isn\'t a realistic time to plan a trip around it.',
    'The Embat beginning to stir at Pollença Bay, still light and inconsistent.',
    'The Embat beginning to stir at Pollença Bay, still light and inconsistent.',
    'The Embat beginning to stir at Pollença Bay, still light and inconsistent.',
    'The Embat building at Pollença Bay.',
    'Peak Embat season at Pollença Bay — the thermal sea breeze at its most reliable.',
    'Peak Embat season at Pollença Bay — the thermal sea breeze at its most reliable.',
    'Peak Embat season at Pollença Bay — the thermal sea breeze at its most reliable.',
    'The Embat still active at Pollença Bay, easing from peak.',
    'The Embat fading at Pollença Bay as summer ends.',
    'Winter at Pollença Bay — the Embat thermal wind isn\'t active, and this isn\'t a realistic time to plan a trip around it.',
    'Winter at Pollença Bay — the Embat thermal wind isn\'t active, and this isn\'t a realistic time to plan a trip around it.',
  ],
  taiwan: [
    'Peak northeast monsoon season at Kenting — the strongest, most reliable wind of the year.',
    'Still strong monsoon wind at Kenting, easing from peak.',
    'Still strong monsoon wind at Kenting, easing from peak.',
    'The monsoon wind fading at Kenting as the season winds down.',
    'The genuine dead spot at Kenting — between the monsoon and typhoon seasons, with the least reliable wind of the year.',
    'The genuine dead spot at Kenting — between the monsoon and typhoon seasons, with the least reliable wind of the year.',
    'A real, if riskier, secondary wind bump at Kenting from typhoon-adjacent systems.',
    'A real, if riskier, secondary wind bump at Kenting from typhoon-adjacent systems.',
    'A quieter stretch at Kenting, between the summer bump and the returning monsoon.',
    'The northeast monsoon returning at Kenting, building toward peak.',
    'Strong monsoon season at Kenting, approaching the winter peak.',
    'Strong monsoon season at Kenting, approaching the winter peak.',
  ],
  bordeaux: [
    'Winter at the Bassin d\'Arcachon — genuinely too calm for a realistic kitesurfing trip.',
    'Wind picking up at the Bassin d\'Arcachon as winter eases.',
    'Wind picking up at the Bassin d\'Arcachon as winter eases.',
    'Building toward the main season at the Bassin d\'Arcachon.',
    'The main wind season at the Bassin d\'Arcachon — consistent, reliable conditions.',
    'The main wind season at the Bassin d\'Arcachon — consistent, reliable conditions.',
    'The main wind season at the Bassin d\'Arcachon — consistent, reliable conditions.',
    'The main wind season at the Bassin d\'Arcachon — consistent, reliable conditions.',
    'The main wind season at the Bassin d\'Arcachon — consistent, reliable conditions.',
    'Still solid wind at the Bassin d\'Arcachon, easing from the main season.',
    'Winter at the Bassin d\'Arcachon — genuinely too calm for a realistic kitesurfing trip.',
    'Winter at the Bassin d\'Arcachon — genuinely too calm for a realistic kitesurfing trip.',
  ],
  'colombian-caribbean': [
    'Strong, reliable trade winds at Cabo de la Vela.',
    'Peak trade-wind season at Cabo de la Vela — among the most consistent kitesurfing conditions anywhere.',
    'Peak trade-wind season at Cabo de la Vela — among the most consistent kitesurfing conditions anywhere.',
    'Peak trade-wind season at Cabo de la Vela — among the most consistent kitesurfing conditions anywhere.',
    'The one real dip at Cabo de la Vela — wind is noticeably less consistent than the rest of the year.',
    'The one real dip at Cabo de la Vela — wind is noticeably less consistent than the rest of the year.',
    'Strong, reliable trade winds at Cabo de la Vela, consistent with this spot\'s near-year-round reputation.',
    'Strong, reliable trade winds at Cabo de la Vela, consistent with this spot\'s near-year-round reputation.',
    'Strong, reliable trade winds at Cabo de la Vela, consistent with this spot\'s near-year-round reputation.',
    'Strong, reliable trade winds at Cabo de la Vela, consistent with this spot\'s near-year-round reputation.',
    'Strong, reliable trade winds at Cabo de la Vela, consistent with this spot\'s near-year-round reputation.',
    'Strong, reliable trade winds at Cabo de la Vela, consistent with this spot\'s near-year-round reputation.',
  ],
  madagascar: [
    'Cyclone season at Ifaty — genuinely the least reliable stretch of the year for wind.',
    'Cyclone season at Ifaty — genuinely the least reliable stretch of the year for wind.',
    'Cyclone season at Ifaty — genuinely the least reliable stretch of the year for wind.',
    'Trade winds building at Ifaty as cyclone season eases.',
    'Trade winds building at Ifaty as cyclone season eases.',
    'Trade winds strengthening further at Ifaty.',
    'Peak trade-wind season at Ifaty — the strongest, most reliable wind of the year.',
    'Peak trade-wind season at Ifaty — the strongest, most reliable wind of the year.',
    'Still solid trade winds at Ifaty, easing from peak.',
    'Trade winds fading at Ifaty as cyclone season approaches.',
    'Trade winds fading at Ifaty as cyclone season approaches.',
    'Cyclone season at Ifaty — genuinely the least reliable stretch of the year for wind.',
  ],
  jamaica: [
    'Peak trade-wind season on Jamaica\'s north coast — the most consistent wind of the year.',
    'Peak trade-wind season on Jamaica\'s north coast — the most consistent wind of the year.',
    'Still solid trade winds on Jamaica\'s north coast, easing from peak.',
    'Still solid trade winds on Jamaica\'s north coast, easing from peak.',
    'Still solid trade winds on Jamaica\'s north coast, easing from peak.',
    'Trade winds fading on Jamaica\'s north coast as hurricane season approaches.',
    'The trade winds are largely gone on Jamaica\'s north coast — a real, if not yet total, dip.',
    'The trade winds are largely gone on Jamaica\'s north coast — a real, if not yet total, dip.',
    'The genuine dead stretch on Jamaica\'s north coast, deep in hurricane season — not a realistic time to plan a wind-sports trip.',
    'The genuine dead stretch on Jamaica\'s north coast, deep in hurricane season — not a realistic time to plan a wind-sports trip.',
    'Trade winds returning to Jamaica\'s north coast.',
    'Trade winds building back toward the winter peak on Jamaica\'s north coast.',
  ],
  rio: [
    'A relatively solid month for wind at Barra da Tijuca, within Rio\'s more reliable stretch.',
    'Wind easing at Barra da Tijuca.',
    'The clear low point of the year at Barra da Tijuca — genuinely the least reliable month for wind.',
    'A modest, middling stretch at Barra da Tijuca — real but unremarkable wind.',
    'A modest, middling stretch at Barra da Tijuca — real but unremarkable wind.',
    'A modest, middling stretch at Barra da Tijuca — real but unremarkable wind.',
    'A modest, middling stretch at Barra da Tijuca — real but unremarkable wind.',
    'Wind picking back up at Barra da Tijuca.',
    'Wind picking back up at Barra da Tijuca.',
    'Rio\'s more reliable stretch for wind at Barra da Tijuca, though still a modest, local-scale scene.',
    'Rio\'s more reliable stretch for wind at Barra da Tijuca, though still a modest, local-scale scene.',
    'Rio\'s more reliable stretch for wind at Barra da Tijuca, though still a modest, local-scale scene.',
  ],
  bahamas: [
    'Peak trade-wind season in the Exumas — the most reliable wind of the year.',
    'Peak trade-wind season in the Exumas — the most reliable wind of the year.',
    'Still solid trade winds in the Exumas, easing from peak.',
    'Still solid trade winds in the Exumas, easing from peak.',
    'Trade winds fading in the Exumas as hurricane season begins.',
    'Hurricane season in the Exumas — a genuine dead stretch, not a realistic time to plan a kitesurfing trip.',
    'Hurricane season in the Exumas — a genuine dead stretch, not a realistic time to plan a kitesurfing trip.',
    'Hurricane season in the Exumas — a genuine dead stretch, not a realistic time to plan a kitesurfing trip.',
    'Hurricane season in the Exumas — a genuine dead stretch, not a realistic time to plan a kitesurfing trip.',
    'Hurricane season in the Exumas — a genuine dead stretch, not a realistic time to plan a kitesurfing trip.',
    'Trade winds returning to the Exumas, building back toward the winter peak.',
    'Trade winds returning to the Exumas, building back toward the winter peak.',
  ],
  bali: [
    'The wet season at Sanur — essentially windless, and not a realistic time to plan a kitesurfing trip.',
    'The wet season at Sanur — essentially windless, and not a realistic time to plan a kitesurfing trip.',
    'The wet season at Sanur — essentially windless, and not a realistic time to plan a kitesurfing trip.',
    'Trade winds beginning to stir at Sanur as the dry season starts.',
    'Trade winds beginning to stir at Sanur as the dry season starts.',
    'Trade winds building at Sanur, though still genuinely light.',
    'Peak season at Sanur — the most wind of the year, though still light by global standards, with larger kites the norm.',
    'Peak season at Sanur — the most wind of the year, though still light by global standards, with larger kites the norm.',
    'Trade winds easing at Sanur, still present.',
    'Trade winds fading further at Sanur as the dry season ends.',
    'The wet season at Sanur — essentially windless, and not a realistic time to plan a kitesurfing trip.',
    'The wet season at Sanur — essentially windless, and not a realistic time to plan a kitesurfing trip.',
  ],
  chicago: [
    'Outside the real wind-sports window at Montrose Beach — the lake\'s calmer months, not a realistic time to plan a session around.',
    'Outside the real wind-sports window at Montrose Beach — the lake\'s calmer months, not a realistic time to plan a session around.',
    'Outside the real wind-sports window at Montrose Beach — the lake\'s calmer months, not a realistic time to plan a session around.',
    'Outside the real wind-sports window at Montrose Beach — the lake\'s calmer months, not a realistic time to plan a session around.',
    'Outside the real wind-sports window at Montrose Beach — the lake\'s calmer months, not a realistic time to plan a session around.',
    'Outside the real wind-sports window at Montrose Beach — the lake\'s calmer months, not a realistic time to plan a session around.',
    'Outside the real wind-sports window at Montrose Beach — the lake\'s calmer months, not a realistic time to plan a session around.',
    'Outside the real wind-sports window at Montrose Beach — the lake\'s calmer months, not a realistic time to plan a session around.',
    'Storm season building at Montrose Beach on Lake Michigan.',
    'Storm season building at Montrose Beach on Lake Michigan.',
    'The best window of the year at Montrose Beach — peak fall storm wind, though still a small, dedicated-local scene.',
    'Storm season easing at Montrose Beach as ice begins to threaten access.',
  ],
  'cape-cod-islands': [
    'Outside the real season on Cape Cod Bay — too cold and calm for a realistic wind-sports trip.',
    'Outside the real season on Cape Cod Bay — too cold and calm for a realistic wind-sports trip.',
    'Outside the real season on Cape Cod Bay — too cold and calm for a realistic wind-sports trip.',
    'Outside the real season on Cape Cod Bay — too cold and calm for a realistic wind-sports trip.',
    'Outside the real season on Cape Cod Bay — too cold and calm for a realistic wind-sports trip.',
    'The wind season beginning on Cape Cod Bay.',
    'The best stretch of the year on Cape Cod Bay, though still a modest, regional-scale scene.',
    'The best stretch of the year on Cape Cod Bay, though still a modest, regional-scale scene.',
    'Still within the wind season on Cape Cod Bay, easing from summer\'s peak.',
    'Outside the real season on Cape Cod Bay — too cold and calm for a realistic wind-sports trip.',
    'Outside the real season on Cape Cod Bay — too cold and calm for a realistic wind-sports trip.',
    'Outside the real season on Cape Cod Bay — too cold and calm for a realistic wind-sports trip.',
  ],
  nyc: [
    'Outside the real season at Rockaway Beach — not a realistic time to plan a wind-sports session around.',
    'Outside the real season at Rockaway Beach — not a realistic time to plan a wind-sports session around.',
    'Outside the real season at Rockaway Beach — not a realistic time to plan a wind-sports session around.',
    'Outside the real season at Rockaway Beach — not a realistic time to plan a wind-sports session around.',
    'Outside the real season at Rockaway Beach — not a realistic time to plan a wind-sports session around.',
    'The wind season beginning at Rockaway Beach.',
    'The best stretch of the year at Rockaway Beach, though still a small, niche scene.',
    'The best stretch of the year at Rockaway Beach, though still a small, niche scene.',
    'Still within the wind season at Rockaway Beach, easing from summer\'s peak.',
    'Outside the real season at Rockaway Beach — not a realistic time to plan a wind-sports session around.',
    'Outside the real season at Rockaway Beach — not a realistic time to plan a wind-sports session around.',
    'Outside the real season at Rockaway Beach — not a realistic time to plan a wind-sports session around.',
  ],
  'big-island': [
    'The calmest stretch of the year for wind on the Big Island\'s coast.',
    'The calmest stretch of the year for wind on the Big Island\'s coast.',
    'The calmest stretch of the year for wind on the Big Island\'s coast.',
    'Conditions improving on the Big Island\'s coast.',
    'The most workable stretch of the year for wind on the Big Island\'s coast, though this remains a minor, undeveloped scene.',
    'The most workable stretch of the year for wind on the Big Island\'s coast, though this remains a minor, undeveloped scene.',
    'The most workable stretch of the year for wind on the Big Island\'s coast, though this remains a minor, undeveloped scene.',
    'The most workable stretch of the year for wind on the Big Island\'s coast, though this remains a minor, undeveloped scene.',
    'The most workable stretch of the year for wind on the Big Island\'s coast, though this remains a minor, undeveloped scene.',
    'Conditions easing on the Big Island\'s coast.',
    'The calmest stretch of the year for wind on the Big Island\'s coast.',
    'The calmest stretch of the year for wind on the Big Island\'s coast.',
  ],
  copenhagen: [
    'Outside the real season at Amager Strandpark — too cold and calm for a realistic wind-sports trip.',
    'Outside the real season at Amager Strandpark — too cold and calm for a realistic wind-sports trip.',
    'Outside the real season at Amager Strandpark — too cold and calm for a realistic wind-sports trip.',
    'Outside the real season at Amager Strandpark — too cold and calm for a realistic wind-sports trip.',
    'The wind season beginning at Amager Strandpark.',
    'The best stretch of the year at Amager Strandpark, though still a modest, local-scale scene.',
    'The best stretch of the year at Amager Strandpark, though still a modest, local-scale scene.',
    'The best stretch of the year at Amager Strandpark, though still a modest, local-scale scene.',
    'Still within the wind season at Amager Strandpark, easing from summer\'s peak.',
    'Outside the real season at Amager Strandpark — too cold and calm for a realistic wind-sports trip.',
    'Outside the real season at Amager Strandpark — too cold and calm for a realistic wind-sports trip.',
    'Outside the real season at Amager Strandpark — too cold and calm for a realistic wind-sports trip.',
  ],
  sydney: [
    'Peak nor\'easter sea-breeze season at Kurnell — the most reliable wind of the year.',
    'Peak nor\'easter sea-breeze season at Kurnell — the most reliable wind of the year.',
    'Still solid sea breeze at Kurnell, easing from peak.',
    'A modest, real baseline at Kurnell — genuine wind, just short of the nor\'easter season\'s reliability.',
    'A modest, real baseline at Kurnell — genuine wind, just short of the nor\'easter season\'s reliability.',
    'A modest, real baseline at Kurnell — genuine wind, just short of the nor\'easter season\'s reliability.',
    'A modest, real baseline at Kurnell — genuine wind, just short of the nor\'easter season\'s reliability.',
    'A modest, real baseline at Kurnell — genuine wind, just short of the nor\'easter season\'s reliability.',
    'A modest, real baseline at Kurnell — genuine wind, just short of the nor\'easter season\'s reliability.',
    'The nor\'easter sea-breeze season building at Kurnell.',
    'The nor\'easter sea-breeze season building at Kurnell.',
    'Peak nor\'easter sea-breeze season at Kurnell — the most reliable wind of the year.',
  ],
  'nova-scotia': [
    'The only genuinely impractical months at Lawrencetown Beach — too cold for a realistic session.',
    'The only genuinely impractical months at Lawrencetown Beach — too cold for a realistic session.',
    'A modest, consistent local wind-sports scene at Lawrencetown Beach, real but small in scale year-round.',
    'A modest, consistent local wind-sports scene at Lawrencetown Beach, real but small in scale year-round.',
    'A modest, consistent local wind-sports scene at Lawrencetown Beach, real but small in scale year-round.',
    'A modest, consistent local wind-sports scene at Lawrencetown Beach, real but small in scale year-round.',
    'A modest, consistent local wind-sports scene at Lawrencetown Beach, real but small in scale year-round.',
    'A modest, consistent local wind-sports scene at Lawrencetown Beach, real but small in scale year-round.',
    'A modest, consistent local wind-sports scene at Lawrencetown Beach, real but small in scale year-round.',
    'A modest, consistent local wind-sports scene at Lawrencetown Beach, real but small in scale year-round.',
    'A modest, consistent local wind-sports scene at Lawrencetown Beach, real but small in scale year-round.',
    'A modest, consistent local wind-sports scene at Lawrencetown Beach, real but small in scale year-round.',
  ],
};

function loadDotEnvLocal(): Record<string, string> {
  const out: Record<string, string> = {};
  const raw = readFileSync(join(__dirname, '..', '.env.local'), 'utf8');
  for (const line of raw.split('\n')) {
    const t = line.trim();
    if (!t || t.startsWith('#')) continue;
    const i = t.indexOf('=');
    if (i === -1) continue;
    let v = t.slice(i + 1).trim();
    if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) v = v.slice(1, -1);
    out[t.slice(0, i).trim()] = v;
  }
  return out;
}

async function main() {
  const env = loadDotEnvLocal();
  if (!env.DATABASE_URL) { console.error('No DATABASE_URL'); process.exit(1); }
  const dryRun = process.argv.includes('--dry-run');
  const db = drizzlePostgres(postgres(env.DATABASE_URL, { prepare: false }));

  for (const id of Object.keys(OVERVIEWS)) {
    const [row] = await db.select().from(places).where(eq(places.id, id));
    if (!row) { console.error(`${id}: not found`); process.exit(1); }
    if (MONTHLY[id].length !== 12) { console.error(`${id}: monthly array is not length 12`); process.exit(1); }
    const patch: Record<string, unknown> = {
      sliderOverview: { ...(row.sliderOverview as Record<string, string>), [KEY]: OVERVIEWS[id] },
      sliderMonthlyWeather: { ...(row.sliderMonthlyWeather as Record<string, (string | null)[]>), [KEY]: MONTHLY[id] },
    };
    console.log(`  ${id}`);
    if (!dryRun) {
      const after = { ...row, ...patch };
      await db.transaction(async (tx) => {
        await tx.update(places).set({ ...patch, updatedAt: new Date() }).where(eq(places.id, id));
        await tx.insert(adminAuditLog).values({
          actorId: '00000000-0000-0000-0000-000000000000', entityType: 'destination', entityId: id,
          action: 'update', beforeValue: row, afterValue: after,
        });
      });
    }
  }
  console.log(dryRun ? '\ndry run — nothing written.' : '\ndone.');
  process.exit(0);
}

main().catch((err) => { console.error(err); process.exit(1); });
