import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

/**
 * Regenerates the per-interest score cutoffs used to DERIVE a signature
 * tier when none has been authored (see deriveSignatureTier in rank.ts).
 *
 * Why per-interest rather than one global scale: a 7 means different things
 * for different interests. Among destinations authored for nationalParks a
 * 7 is mid-pack; among those authored for safari it is near the top. The
 * question the tier answers — "is this place notable FOR this thing" — is
 * inherently relative to the other destinations claiming that same
 * interest, so the cutoffs have to be too.
 *
 * Only authored, non-N/A scores count toward a distribution: a destination
 * that has explicitly said an interest doesn't apply is not competing for
 * it and shouldn't drag the percentiles down.
 *
 * Run after any material content change; scripts/audit-* will show drift.
 */

const DERIVED = new Set(['deals', 'crowds']);
const OUT = join(__dirname, '..', 'src', 'lib', 'scoring', 'interestThresholds.ts');

function loadDotEnvLocal(): Record<string, string> {
  const out: Record<string, string> = {};
  let raw: string;
  try {
    raw = readFileSync(join(__dirname, '..', '.env.local'), 'utf8');
  } catch {
    return out;
  }
  for (const line of raw.split('\n')) {
    const t = line.trim();
    if (!t || t.startsWith('#')) continue;
    const i = t.indexOf('=');
    if (i === -1) continue;
    const key = t.slice(0, i).trim();
    let value = t.slice(i + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

function quantile(sorted: number[], q: number): number {
  if (!sorted.length) return 0;
  const i = (sorted.length - 1) * q;
  const lo = Math.floor(i), hi = Math.ceil(i);
  return lo === hi ? sorted[lo] : sorted[lo] + (sorted[hi] - sorted[lo]) * (i - lo);
}

async function main() {
  const env = loadDotEnvLocal();
  if (!env.DATABASE_URL) {
    console.error('No DATABASE_URL in .env.local — refusing to run against the PGlite fallback.');
    process.exit(1);
  }
  process.env.DATABASE_URL = env.DATABASE_URL;

  const { eq } = await import('drizzle-orm');
  const { db } = await import('../src/lib/db/client');
  const { places } = await import('../src/lib/db/schema');
  const { SLIDERS } = await import('../src/lib/scoring/constants');

  const rows = await db
    .select({ baseScores: places.baseScores, naSliders: places.naSliders })
    .from(places)
    .where(eq(places.isPrimaryDestination, true));

  const keys = SLIDERS.map((s) => s.key).filter((k) => !DERIVED.has(k));
  const table: Record<string, { signature: number; strong: number; casual: number; n: number }> = {};

  console.log('interest'.padEnd(24) + 'n'.padStart(5) + 'p90'.padStart(6) + 'p75'.padStart(6) + '  -> signature / strong / casual');
  for (const k of keys) {
    const scores: number[] = [];
    for (const r of rows) {
      if ((r.naSliders ?? []).includes(k)) continue;
      const v = (r.baseScores as Record<string, number>)[k];
      if (v !== undefined && v > 0) scores.push(v);
    }
    scores.sort((a, b) => a - b);
    const p90 = quantile(scores, 0.9);
    const p75 = quantile(scores, 0.75);
    // Absolute floors stop a thinly-authored interest from crowning a
    // mediocre score: being top-decile among six destinations is not the
    // same as being notable for the thing.
    const signature = Math.max(p90, 8);
    const strong = Math.max(p75, 6);
    const casual = 4;
    table[k] = { signature, strong, casual, n: scores.length };
    console.log(
      k.padEnd(24) + String(scores.length).padStart(5) + p90.toFixed(1).padStart(6) + p75.toFixed(1).padStart(6) +
      `  -> ${signature.toFixed(1)} / ${strong.toFixed(1)} / ${casual.toFixed(1)}`,
    );
  }

  const body = `/**
 * GENERATED by scripts/generate-interest-thresholds.ts — do not hand-edit.
 *
 * Score cutoffs per interest, used to derive a signature tier when a
 * destination has none authored. Derived from the live catalogue: within
 * each interest, the 90th and 75th percentiles of authored, non-N/A
 * scores, floored at 8 and 6 respectively so a thinly-authored interest
 * cannot crown a mediocre score.
 *
 * Regenerate after material content changes.
 * Generated: ${new Date().toISOString().slice(0, 10)} from ${rows.length} destinations.
 */
export interface InterestThreshold {
  /** score at or above which a destination is notable for this interest */
  signature: number;
  /** score at or above which it is a genuine draw */
  strong: number;
  /** score at or above which it is present but not a reason to come */
  casual: number;
}

export const INTEREST_THRESHOLDS: Record<string, InterestThreshold> = {
${keys.map((k) => `  ${k}: { signature: ${table[k].signature}, strong: ${table[k].strong}, casual: ${table[k].casual} },`).join('\n')}
};

/** Fallback for an interest with no generated entry. */
export const DEFAULT_THRESHOLD: InterestThreshold = { signature: 8, strong: 6, casual: 4 };

`;
  writeFileSync(OUT, body);
  console.log(`\nwrote ${OUT}`);
  process.exit(0);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
